### ISSUE TITLE
vXX.X Release Checklist

### ISSUE THREAD

**Issue by trojanwarhorse1** [mozilla-mobile/firefox-ios#10320]
Soft freeze:
Hard freeze:

## Soft Freeze Items
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Update SENTRY_DSN secret in Bitrise (per release)
- [x] Add Bitrise trigger for release branch

### Soft Freeze Optional
These items should be completed as soon as possible, preferrably on soft code
freeze day. Due to timing issues, they may not be available until hard code
freeze, and must be completed on hard freeze.

- [x] Ensure string export was completed for L10N (if needed)
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories)
- [x] File P.I. request

## Hard Freeze Items

- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
    - [x] Add volunteer contributions
- [x] Release Notes updated
- [x] Get App Store screenshots and all locales if necessary
- [x] Submit build to Apple
- [x] Release with 7-day rollout

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist-Details) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-3993)

**Comment by lmarceau** [comment]
Closing this as we have other tasks in place for our release processes
