### ISSUE TITLE
v20.1 Release Checklist

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5701]
- [x] Update Version Number in code (Eng task)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Tag release in GitHub (Eng task)
- [x] Create version specific Sentry project
- [x] Setup sentry keys in BuddyBuild (per release)
- [x] File P.I request
- [x] Release Notes updated
- [x] Submit build to apple
- [x] Release with 7-day rollout

**Comment by garvankeeley** [comment]
We use the same release notes as prev. on point releases like this AFAIK.

**Comment by garvankeeley** [comment]
PI req https://jira.mozilla.com/browse/PI-369
