### ISSUE TITLE
v20.2 Release Checklist

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#5768]
- [x] Update Version Number in code (Eng task)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Tag release in GitHub (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
- [x] File P.I. request
- [x] Release Notes updated
- [x] Submit build to Apple
- [ ] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/releases/tag/20.2
