### ISSUE TITLE
FXIOS-189 ⁃ v21.0Release Checklist

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#5817]
- [x] Update Version Number in code (Eng task)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Tag release in GitHub (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
- [x] File P.I. request
- [x] Release Notes updated
- [x] Submit build to Apple
- [x] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-189)

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/releases/tag/21.0
