### ISSUE TITLE
v26.X Release Checklist

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#6694]
- [x] Ensure L10N box has been run (if needed) to do string export
- [x] Update Version Number in code (Eng task)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
- [x] File P.I. request
- [x] Release Notes updated
- [x] Get App Store screenshots and all locales if necessary
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
- [x] Submit build to Apple (Select YES to IDFA, 'Attribute this app installation to a previously served advertisement')
- [x] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

**Comment by garvankeeley** [comment]
Confirming the sec advisory steps were completed https://github.com/mozilla/foundation-security-advisories-private/commit/05fa6218789151cf8631ad82e30c96c5fd3f85d6
(private repo commit)

**Comment by nbhasin2** [comment]
Released v26.0 (18099) with 7 day rollout
