### ISSUE TITLE
v28.0 Release Checklist

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#6976]
Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
---
- [x] Ensure L10N box has been run (if needed) to do string export
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
- [x] File P.I. request
- [x] Release Notes updated
- [x] Submit build to Apple (Select YES to IDFA, 'Attribute this app installation to a previously served advertisement')
- [x] Get App Store screenshots and all locales if necessary
- [x] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

**Comment by garvankeeley** [comment]
Sec advisories handled, final step is making them public when app is released

**Comment by garvankeeley** [comment]
sec advisories done

**Comment by dnarcese** [comment]
Release went out July 29.
