### ISSUE TITLE
FXIOS-806 ⁃ v28.1 Release Checklist

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#7217]
_Soft freeze August 28_

Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
---
- [x] Ensure L10N box has been run (if needed) to do string export
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
- [x] File P.I. request
- [x] Release Notes updated
- [x] no longer: ~Submit build to Apple (Select YES to IDFA, 'Attribute this app installation to a previously served advertisement')~
- [x] Get App Store screenshots and all locales if necessary
- [x] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-806)

**Comment by garvankeeley** [comment]
For the point release we don't need to do `Create version specific Sentry project` and `Setup Sentry keys in BuddyBuild (per release)`, we can use v28 ones for those.
