### ISSUE TITLE
FXIOS-856 ⁃ vXX.X Release Checklist

### ISSUE THREAD

**Issue by anubes19** [mozilla-mobile/firefox-ios#7271]
Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
---
- [x] Ensure L10N box has been run (if needed) to do string export
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
- [x] File P.I. request
- [x] Release Notes updated
- [x] Submit build to Apple (Select YES to IDFA, 'Attribute this app installation to a previously served advertisement')
- [ ] Get App Store screenshots and all locales if necessary
- [ ] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-856)

**Comment by anubes19** [comment]
Y
