### ISSUE TITLE
FXIOS-873 ⁃ v28.2 Release Checklist

### ISSUE THREAD

**Issue by garvankeeley** [mozilla-mobile/firefox-ios#7288]
Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in BuddyBuild (per release)
---
- [x] Ensure L10N box has been run (if needed) to do string export
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
- [x] File P.I. request (https://jira.mozilla.com/browse/PI-803)
- [x] Release Notes updated
- [x] Submit build to Apple, Select NO to IDFA
- [ ] Get App Store screenshots and all locales if necessary
- [ ] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-873)

**Comment by garvankeeley** [comment]
https://github.com/mozilla-mobile/firefox-ios/releases/tag/v28.2

**Comment by garvankeeley** [comment]
Currently blocked on BuddyBuild failing with carthage (internal error)

**Comment by garvankeeley** [comment]
BB fails to support default browser with their auto-provisioning setup, and I don't see how to change that.
Instead, Bitrise is working, https://app.bitrise.io/build/625930bac2b2d64d
