### ISSUE TITLE
FXIOS-1156 ⁃ L10N Migration checklist

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/firefox-ios#7595]
- [ ] Write script to map between `.xcloc` and the current directory structure in the l10n repo
- [ ] When importing locales, check a set of required IDs and backfill with the `en` locale*
- [ ] Test an export in the L10N repo to verify everything looks good
- [ ] Verify we can edit pontoon Filenames. If we can't, we'll have to add that to our script.
- [ ] Lock translations in Pontoon
- [ ] Land PR to fix strings in this repository
- [ ] Work with L10N to get a quick export and import
- [ ] Document new L10N process
- [ ] (bonus) Create export / import actions on Github.

\*
```python
//required_ids = [
//    'NSCameraUsageDescription',
//    'NSLocationWhenInUseUsageDescription',
//    'NSMicrophoneUsageDescription',
//    'NSPhotoLibraryAddUsageDescription',
//    'ShortcutItemTitleNewPrivateTab',
//    'ShortcutItemTitleNewTab',
//    'ShortcutItemTitleQRCode',
//]
// backfill required properties from en locale if missing or app will crash on those locales.
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1156)

**Comment by boek** [comment]
dup of #7571
