### ISSUE TITLE
FXIOS-1158 ⁃ v21.1 Release Checklist

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#7597]
Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Setup Sentry keys in Bitrise (per release)
---
~- [ ] Ensure L10N box has been run (if needed) to do string export~
~- [ ] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories)~
- [ ] Tag release in GitHub (Eng task)
    - [ ] Link to commit diff between versions
- [x] File P.I. request
- [x] Release Notes updated
- [ ] Submit build to Apple (Select NO to IDFA)
- [ ] Get App Store screenshots and all locales if necessary
- [ ] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1158)
