### ISSUE TITLE
FXIOS-1574 ⁃ v32.1 Release Checklist [point release]

### ISSUE THREAD

**Issue by nbhasin2** [mozilla-mobile/firefox-ios#8113]
Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task) - Not required for point release
- [x] Create version specific Sentry project
- [x] Update SENTRY_DSN secret in Bitrise (per release)
---
- [x] Ensure L10N box has been run (if needed) to do string export - Not required for point release
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) - Not required for point release
- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
- [x] File P.I. request - No full PI request required for v32.1 but will ask Simon to test #8106
- [x] Release Notes updated - Using same v32 release notes for v32.1 on iTunesConnect
- [x] Submit build to Apple (Select NO to IDFA)
- [x] Get App Store screenshots and all locales if necessary
- [x] Release with 7-day rollout 

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1574)
