### ISSUE TITLE
FXIOS-1595 ⁃ v33 Release Checklist

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-ios#8149]
Soft freeze: Mar 18
Hard freeze: Mar 22

Branch setup, steps typically done when creating new version branch
- [x] Update Version Number in code (Eng task, use `update_version.sh`)
- [x] Update `Client/Info.plist` MozWhatsNewTopic (Eng task)
- [x] Create version specific Sentry project
- [x] Update SENTRY_DSN secret in Bitrise (per release)
- [x] Add Bitrise trigger for release branch 
---
- [x] Ensure string export was completed for L10N (if needed)
- [x] Check for [security advisories](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist/#security-advisories) 
- [x] Tag release in GitHub (Eng task)
    - [x] Link to commit diff between versions
- [x] File P.I. request
- [x] Release Notes updated
- [x] Submit build to Apple
- [x] Get App Store screenshots and all locales if necessary
- [x] Release with 7-day rollout

See [Release build checklist wiki](https://github.com/mozilla-mobile/firefox-ios/wiki/Release-Build-Checklist) for more detailed instructions.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXIOS-1595)
